// Generated by CoffeeScript 1.6.3
(function() {
  var InstaSlider,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  InstaSlider = (function() {
    function InstaSlider(options) {
      this.options = options;
      this._processFeed = __bind(this._processFeed, this);
      this._createInstafeed = __bind(this._createInstafeed, this);
      this.$container = $('#instaslider');
    }

    InstaSlider.prototype.run = function() {
      var feed;
      feed = this._createInstafeed();
      return feed.run();
    };

    InstaSlider.prototype._createInstafeed = function() {
      this.options.get = 'user';
      this.options.mock = true;
      this.options.success = this._processFeed;
      return new Instafeed(this.options);
    };

    InstaSlider.prototype._createHashtagFilter = function(hashtag) {
      return function(e) {
        return e.tags.indexOf(hashtag) > -1;
      };
    };

    InstaSlider.prototype._feedDataToImgEl = function(data) {
      var titleText, url;
      url = data.images.standard_resolution.url;
      titleText = data.caption.text;
      return $('<img>', {
        src: url,
        title: titleText
      });
    };

    InstaSlider.prototype._sliderFromImages = function(images) {
      var $ul;
      $ul = $('<ul>', {
        "class": 'slides'
      });
      images.forEach(function($img) {
        return $ul.append($('<li>').append($img));
      });
      return $ul;
    };

    InstaSlider.prototype._processFeed = function(response) {
      var data, filteredData, hashtagFilter, images;
      data = response.data;
      if (this.options.filter != null) {
        hashtagFilter = this._createHashtagFilter(this.options.filter);
        filteredData = data.filter(hashtagFilter);
        images = filteredData.map(this._feedDataToImgEl);
      } else {
        images = data.map(this._feedDataToImgEl);
      }
      this.$container.append(this._sliderFromImages(images));
      return this.$container.flexslider(this.options.flexslider || {});
    };

    return InstaSlider;

  })();

  window.InstaSlider = InstaSlider;

}).call(this);
